export const HOME = '/'
export const LOGIN = '/login'
export const SIGN_UP = '/signup'
export const FORGOT_PASSWORD = '/forgotPassword'

export const ROUND = '/klassement/ronde/:ronde'
export const TOTAL_TOTO = '/klassement/totaaltoto'
export const TOTO_ROUND = '/klassement/totoronde/:totoronde'
export const PAGE_NOT_FOUND = '/page-not-found'
export const EDIT_PROFILE = '/profiel/edit'
export const EDIT_PASSWORD = '/profiel/password'
export const PROGRAM = '/programma'
export const RULES = '/regels'
export const SCORES_USER = '/scores'
export const LIST_OF_PLAYERS = '/spelers'
export const SCORES_PLAYERS = '/spelers/:id/scores'
export const PREDICTIONS_PLAYERS =
  '/spelers/:id/voorspellingen/:totoronde/:ronde'
export const PREDICTIONS = '/voorspellingen/:totoronde/:ronde'
export const FIXTURES = '/wedstrijd/:id'
